spring:
  application:
    name: Store

  # Data Base Information
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  # Hibernate ORM Configuration
  # JPA is Jakarta Persistence API
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true